# Generated by Django 5.2 on 2025-06-03 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_setup', '0003_menulink_site_setup'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='favicon',
            field=models.ImageField(blank=True, default='', upload_to='assets/favicon/%Y/%m/'),
        ),
    ]
